[package]
name = "Console-Chat"
version = "0.1.0"
description = "Simple Tui Chat"
authors = ["Thetechnicker <106349149+thetechnicker@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
color-eyre = "0.6.5"
tui-input = { version = "0.14.0", features = ["crossterm"], default-features = false }
reqwest = { version = "0.12.24", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
url = "2.5.7"
log = "0.4.28"
chrono = "0.4.42"
fern = "0.7.1"
tokio-stream = "0.1.17"
bytes = "1.11.0"
base64 = "0.22.1"
alkali = { version = "0.3.0", features = ["use-serde"] }
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = {version="0.3.20", features=["json","local-time"]}
tracing-appender = "0.2.3"
palette = "0.7.6"
clippers = "0.1.2"

[dev-dependencies]
insta = "1.44.3"
lipsum = "0.9.1"
